trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Ensure Java 17 is installed and active
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    architecture: 'x64'

# Optional: check Java version for debugging
- script: java -version
  displayName: 'Check Java Version'

# Run Maven build
- task: Maven@3
  inputs:
    mavenPomFile: 'program6/pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
